// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://plgwjspvmvgfccmnzqaf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsZ3dqc3B2bXZnZmNjbW56cWFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MzExOTAsImV4cCI6MjA2MDQwNzE5MH0.wOHRyW44qmyoLscx6OHUIWvm6l5Lc9bg3MOaAGhNl9s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);